"""User-facing construction facade for protocol-bound VirtualDut modules.

Use :mod:`protocol_model.integrations.recipes.catalog` when the desired module
role is known but its factory name is not.  Import a named builder from this
facade once the construction choice is explicit.
"""

from .amba import (
    Axi4BurstAssemblyProfile,
    Axi4ReadRouteTableProfile,
    Axi4WriteRouteTableProfile,
    ChiIssueHCacheVdutAssembly,
    attach_chi_issue_h_coherence,
    bind_chi_issue_h_cache_vdut,
    build_ahb_address_fabric_vdut,
    build_ahb_address_space_vdut,
    build_ahb_blackhole_sink_vdut,
    build_ahb_idle_source_vdut,
    build_amba_queued_address_responder_vdut,
    build_amba_sensor_fifo_vdut,
    build_amba_serial_address_bridge_vdut,
    build_amba_serial_bridge_vdut,
    build_amba_serial_burst_bridge_vdut,
    build_amba_serialized_memory_copy_vdut,
    build_apb_address_fabric_vdut,
    build_apb_address_space_vdut,
    build_apb_blackhole_sink_vdut,
    build_apb_idle_source_vdut,
    build_axi4_read_crossbar_vdut,
    build_axi4_read_demux_vdut,
    build_axi4_write_crossbar_vdut,
    build_axi4_address_space_vdut,
    build_axi4_blackhole_sink_vdut,
    build_axi4_idle_source_vdut,
    build_axi4_lite_address_crossbar_vdut,
    build_axi4_lite_address_fabric_vdut,
    build_axi4_lite_address_space_vdut,
    build_axi4_lite_to_apb_bridge_vdut,
    build_axi4_stream_capture_vdut,
    build_axi4_to_ahb_lite_bridge_vdut,
    build_axi4_to_apb_bridge_vdut,
    build_chi_issue_h_cache_vdut,
)
from .catalog import (
    VIRTUAL_DUT_RECIPES,
    VirtualDutRecipe,
    VirtualDutRecipeKind,
    VirtualDutRecipeLayer,
    VirtualDutRecipeTier,
    get_virtual_dut_recipe,
    list_virtual_dut_recipes,
    render_virtual_dut_recipe_catalog,
)
from .control import (
    build_edge_interrupt_controller_vdut,
    build_edge_interrupt_target_vdut,
)

__all__ = [
    "Axi4BurstAssemblyProfile",
    "Axi4ReadRouteTableProfile",
    "Axi4WriteRouteTableProfile",
    "ChiIssueHCacheVdutAssembly",
    "VIRTUAL_DUT_RECIPES",
    "VirtualDutRecipe",
    "VirtualDutRecipeKind",
    "VirtualDutRecipeLayer",
    "VirtualDutRecipeTier",
    "attach_chi_issue_h_coherence",
    "bind_chi_issue_h_cache_vdut",
    "build_ahb_address_fabric_vdut",
    "build_ahb_address_space_vdut",
    "build_ahb_blackhole_sink_vdut",
    "build_ahb_idle_source_vdut",
    "build_amba_queued_address_responder_vdut",
    "build_amba_sensor_fifo_vdut",
    "build_amba_serial_address_bridge_vdut",
    "build_amba_serial_bridge_vdut",
    "build_amba_serial_burst_bridge_vdut",
    "build_amba_serialized_memory_copy_vdut",
    "build_apb_address_fabric_vdut",
    "build_apb_address_space_vdut",
    "build_apb_blackhole_sink_vdut",
    "build_apb_idle_source_vdut",
    "build_axi4_read_crossbar_vdut",
    "build_axi4_read_demux_vdut",
    "build_axi4_write_crossbar_vdut",
    "build_axi4_address_space_vdut",
    "build_axi4_blackhole_sink_vdut",
    "build_axi4_idle_source_vdut",
    "build_axi4_lite_address_crossbar_vdut",
    "build_axi4_lite_address_fabric_vdut",
    "build_axi4_lite_address_space_vdut",
    "build_axi4_lite_to_apb_bridge_vdut",
    "build_axi4_stream_capture_vdut",
    "build_axi4_to_ahb_lite_bridge_vdut",
    "build_axi4_to_apb_bridge_vdut",
    "build_chi_issue_h_cache_vdut",
    "build_edge_interrupt_controller_vdut",
    "build_edge_interrupt_target_vdut",
    "get_virtual_dut_recipe",
    "list_virtual_dut_recipes",
    "render_virtual_dut_recipe_catalog",
]
