"""Explicit VirtualDut recipe inventory.

This file is intentionally declarative.  File-system scanning and decorator
registration would make the available construction surface depend on import
order and would blur the difference between a helper and a supported recipe.
"""

from __future__ import annotations

from .model import (
    VirtualDutRecipe,
    VirtualDutRecipeKind as Kind,
    VirtualDutRecipeLayer as Layer,
    VirtualDutRecipeTier as Tier,
)


_CORE = "protocol_model.virtual_dut.recipes"
_AMBA = "protocol_model.integrations.recipes.amba"
_AMBA_CHI = "protocol_model.integrations.recipes.amba.chi"
_CONTROL = "protocol_model.integrations.recipes.control"


VIRTUAL_DUT_RECIPES: tuple[VirtualDutRecipe, ...] = (
    # Protocol-neutral composition roots.  These require prepared bindings.
    VirtualDutRecipe(
        id="core.fixture.idle-source",
        title="Idle source",
        kind=Kind.FIXTURE,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_idle_source_vdut",
        operation_form="canonical-event",
        protocol_scope=("caller-supplied InterfaceProtocol",),
        port_shape="1 source",
        summary="Declare a source boundary that emits no autonomous traffic.",
        required_inputs=("InterfaceProtocol", "source role"),
    ),
    VirtualDutRecipe(
        id="core.fixture.blackhole-sink",
        title="Blackhole sink",
        kind=Kind.FIXTURE,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_blackhole_sink_vdut",
        operation_form="canonical-event",
        protocol_scope=("caller-supplied InterfaceProtocol",),
        port_shape="1 sink",
        summary="Consume boundary traffic without producing a completion.",
        required_inputs=("InterfaceProtocol", "sink role"),
    ),
    VirtualDutRecipe(
        id="core.endpoint.queued-address-responder",
        title="Queued address responder",
        kind=Kind.ENDPOINT,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_queued_address_responder_vdut",
        operation_form="address-access",
        protocol_scope=("prepared address completer binding",),
        port_shape="1..N completers",
        summary="Serve address accesses through a finite FIFO and explicit delay policy.",
        required_inputs=("prepared bindings", "AddressSpace", "queue capacity"),
    ),
    VirtualDutRecipe(
        id="core.endpoint.sensor-fifo",
        title="Sensor FIFO",
        kind=Kind.ENDPOINT,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_sensor_fifo_vdut",
        operation_form="address-access",
        protocol_scope=("prepared address completer binding",),
        port_shape="1 completer",
        summary="Expose explicitly sampled data through a finite address-visible FIFO.",
        required_inputs=("prepared binding", "SensorFifoConfig"),
    ),
    VirtualDutRecipe(
        id="core.initiator.serialized-memory-copy",
        title="Serialized memory-copy engine",
        kind=Kind.INITIATOR,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_serialized_memory_copy_vdut",
        operation_form="address-access",
        protocol_scope=("prepared address requester binding",),
        port_shape="1 requester",
        summary="Issue alternating read and write accesses for one copy descriptor.",
        required_inputs=("prepared binding", "MemoryCopyDescriptor"),
    ),
    VirtualDutRecipe(
        id="core.control.priority-interrupt-controller",
        title="Priority interrupt controller",
        kind=Kind.CONTROL,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_priority_interrupt_controller_vdut",
        operation_form="notification",
        protocol_scope=("prepared notification bindings",),
        port_shape="N ingress + 1 target",
        summary="Prioritize edge notifications and retain ownership until EOI.",
        required_inputs=("ingress bindings", "target binding"),
    ),
    VirtualDutRecipe(
        id="core.control.explicit-eoi-target",
        title="Explicit-EOI interrupt target",
        kind=Kind.CONTROL,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_explicit_eoi_interrupt_target_vdut",
        operation_form="notification",
        protocol_scope=("prepared notification target binding",),
        port_shape="1 target",
        summary="Capture a notification and complete it through explicit EOI.",
        required_inputs=("prepared binding",),
    ),
    VirtualDutRecipe(
        id="core.bridge.address-translation",
        title="Address-access translation bridge",
        kind=Kind.BRIDGE,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_address_translation_vdut",
        operation_form="address-access",
        protocol_scope=("prepared ingress binding", "prepared egress binding"),
        port_shape="1 ingress -> 1 egress",
        summary="Execute a typed single-access translation plan and return completion.",
        required_inputs=("two prepared bindings", "TranslationPlan"),
    ),
    VirtualDutRecipe(
        id="core.bridge.address-operation-translation",
        title="Grouped address-operation bridge",
        kind=Kind.BRIDGE,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_address_operation_translation_vdut",
        operation_form="address-operation",
        protocol_scope=("prepared ingress binding", "prepared egress binding"),
        port_shape="1 ingress -> 1 egress",
        summary="Translate grouped or burst operations with child completion folding.",
        required_inputs=("two prepared bindings", "TranslationPlan"),
    ),
    VirtualDutRecipe(
        id="core.fabric.scheduled-address-crossbar",
        title="Scheduled address crossbar",
        kind=Kind.FABRIC,
        layer=Layer.CORE,
        tier=Tier.FOUNDATION,
        factory_path=f"{_CORE}:build_scheduled_address_crossbar_vdut",
        operation_form="address-access",
        protocol_scope=("prepared address bindings",),
        port_shape="N ingress -> M egress",
        summary="Route queued accesses with per-egress arbitration and owner return.",
        required_inputs=("ingress bindings", "egress bindings", "address routes"),
    ),

    # Protocol-bound AMBA endpoints and network experiment components.
    VirtualDutRecipe(
        id="amba.endpoint.queued-address-responder",
        title="AMBA queued address responder",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_amba_queued_address_responder_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite", "AHB-Lite/AHB5", "APB3/APB4/APB5"),
        port_shape="1 completer",
        summary="Bind the finite queued responder to a supported AMBA access protocol.",
        required_inputs=("InterfaceProtocol", "AddressSpace", "queue policy"),
        example="showcase/demos/vdut/apb4_queued_responder",
    ),
    VirtualDutRecipe(
        id="amba.endpoint.sensor-fifo",
        title="AMBA sensor FIFO",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_amba_sensor_fifo_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite", "AHB-Lite/AHB5", "APB3/APB4/APB5"),
        port_shape="1 completer",
        summary="Bind the address-visible sensor FIFO to a supported AMBA protocol.",
        required_inputs=("InterfaceProtocol", "SensorFifoConfig"),
        example="showcase/demos/vdut/sensor_dma_capture",
    ),
    VirtualDutRecipe(
        id="amba.initiator.serialized-memory-copy",
        title="AMBA serialized memory-copy engine",
        kind=Kind.INITIATOR,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_amba_serialized_memory_copy_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4", "AXI4-Lite", "AHB-Lite/AHB5", "APB3/APB4/APB5"),
        port_shape="1 requester",
        summary="Bind the single-outstanding copy engine to a supported AMBA protocol.",
        required_inputs=("InterfaceProtocol", "MemoryCopyDescriptor"),
        example="showcase/demos/vdut/sensor_dma_capture",
    ),
    VirtualDutRecipe(
        id="amba.chi.endpoint.coherent-cache",
        title="CHI Issue H coherent cache participant",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA_CHI}:build_chi_issue_h_cache_vdut",
        operation_form="coherent cache-line lifecycle",
        protocol_scope=("AMBA CHI Issue H restricted RN-F profile",),
        port_shape="1 directed TX bundle + 1 directed RX bundle",
        summary=(
            "Attach CHI permission and transaction behavior to a "
            "protocol-neutral cache-line store."
        ),
        required_inputs=(
            "CacheCore, or initial cache lines for the convenience factory",
            "RN NodeID",
            "Home NodeID",
        ),
    ),
    VirtualDutRecipe(
        id="amba.endpoint.apb-address-space",
        title="APB address space",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_apb_address_space_vdut",
        operation_form="address-access",
        protocol_scope=("APB3", "APB4", "APB5"),
        port_shape="1 completer",
        summary="Expose a reference AddressSpace behind an APB completer port.",
        required_inputs=("APB InterfaceProtocol", "AddressSpace"),
        example="showcase/demos/vdut/axi_ahb_apb_chain",
    ),
    VirtualDutRecipe(
        id="amba.endpoint.ahb-address-space",
        title="AHB address space",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_ahb_address_space_vdut",
        operation_form="address-access",
        protocol_scope=("AHB-Lite", "AHB5"),
        port_shape="1 completer",
        summary="Expose a reference AddressSpace behind an AHB subordinate port.",
        required_inputs=("AHB InterfaceProtocol", "AddressSpace"),
    ),
    VirtualDutRecipe(
        id="amba.endpoint.axi4-lite-address-space",
        title="AXI4-Lite address space",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_lite_address_space_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite",),
        port_shape="1 completer",
        summary="Expose a reference AddressSpace behind an AXI4-Lite subordinate port.",
        required_inputs=("AXI4-Lite InterfaceProtocol", "AddressSpace"),
    ),
    VirtualDutRecipe(
        id="amba.endpoint.axi4-address-space",
        title="AXI4 address space",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_address_space_vdut",
        operation_form="address-operation",
        protocol_scope=("AXI4",),
        port_shape="1 completer",
        summary=(
            "Expose a reference AddressSpace behind a full AXI4 subordinate "
            "port, optionally with bounded caller-stepped R/B emission."
        ),
        required_inputs=("AXI4 InterfaceProtocol", "AddressSpace"),
    ),
    VirtualDutRecipe(
        id="amba.endpoint.axi4-stream-capture",
        title="AXI4-Stream capture endpoint",
        kind=Kind.ENDPOINT,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_stream_capture_vdut",
        operation_form="stream-transfer",
        protocol_scope=("AXI4-Stream",),
        port_shape="1 sink",
        summary="Decode and retain ordered AXI4-Stream transfers.",
        required_inputs=("AXI4-Stream InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.apb-idle-source",
        title="APB idle source",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_apb_idle_source_vdut",
        operation_form="canonical-event",
        protocol_scope=("APB3", "APB4", "APB5"),
        port_shape="1 requester",
        summary="Construct a silent APB requester boundary.",
        required_inputs=("APB InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.apb-blackhole-sink",
        title="APB blackhole sink",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_apb_blackhole_sink_vdut",
        operation_form="canonical-event",
        protocol_scope=("APB3", "APB4", "APB5"),
        port_shape="1 completer",
        summary="Construct an APB completer boundary that never completes a request.",
        required_inputs=("APB InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.ahb-idle-source",
        title="AHB idle source",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_ahb_idle_source_vdut",
        operation_form="canonical-event",
        protocol_scope=("AHB-Lite", "AHB5"),
        port_shape="1 manager",
        summary="Construct a silent AHB manager boundary.",
        required_inputs=("AHB InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.ahb-blackhole-sink",
        title="AHB blackhole sink",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_ahb_blackhole_sink_vdut",
        operation_form="canonical-event",
        protocol_scope=("AHB-Lite", "AHB5"),
        port_shape="1 subordinate",
        summary="Construct an AHB subordinate boundary that never completes a request.",
        required_inputs=("AHB InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.axi4-idle-source",
        title="AXI4 idle source",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_axi4_idle_source_vdut",
        operation_form="canonical-event",
        protocol_scope=("AXI4",),
        port_shape="1 manager",
        summary="Construct a silent AXI4 manager boundary.",
        required_inputs=("AXI4 InterfaceProtocol",),
    ),
    VirtualDutRecipe(
        id="amba.fixture.axi4-blackhole-sink",
        title="AXI4 blackhole sink",
        kind=Kind.FIXTURE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_axi4_blackhole_sink_vdut",
        operation_form="canonical-event",
        protocol_scope=("AXI4",),
        port_shape="1 subordinate",
        summary="Construct an AXI4 subordinate boundary that leaves requests pending.",
        required_inputs=("AXI4 InterfaceProtocol",),
    ),

    # Multi-port AMBA routing products.
    VirtualDutRecipe(
        id="amba.fabric.apb-single-ingress",
        title="APB address fabric",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_apb_address_fabric_vdut",
        operation_form="address-access",
        protocol_scope=("APB3", "APB4", "APB5"),
        port_shape="1 ingress -> N egress",
        summary="Bind a decoder/response-mux address fabric to APB ports.",
        required_inputs=("APB InterfaceProtocol", "address routes"),
        example="showcase/demos/vdut/axi_ahb_apb_chain",
    ),
    VirtualDutRecipe(
        id="amba.fabric.ahb-single-ingress",
        title="AHB address fabric",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_ahb_address_fabric_vdut",
        operation_form="address-access",
        protocol_scope=("AHB-Lite", "AHB5"),
        port_shape="1 ingress -> N egress",
        summary="Bind a decoder/response-mux address fabric to AHB ports.",
        required_inputs=("AHB InterfaceProtocol", "address routes"),
    ),
    VirtualDutRecipe(
        id="amba.fabric.axi4-lite-single-ingress",
        title="AXI4-Lite address fabric",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_lite_address_fabric_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite",),
        port_shape="1 ingress -> N egress",
        summary="Bind a decoder/response-mux address fabric to AXI4-Lite ports.",
        required_inputs=("AXI4-Lite InterfaceProtocol", "address routes"),
    ),
    VirtualDutRecipe(
        id="amba.fabric.axi4-lite-crossbar",
        title="AXI4-Lite scheduled crossbar",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_lite_address_crossbar_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite",),
        port_shape="N ingress -> M egress",
        summary="Bind queued routing, arbitration, and owner return to AXI4-Lite ports.",
        required_inputs=("AXI4-Lite InterfaceProtocol", "port names", "address routes"),
        example="showcase/demos/vdut/axi4_lite_2x2_crossbar",
    ),
    VirtualDutRecipe(
        id="amba.fabric.axi4-read-crossbar",
        title="AXI4 AR/R crossbar",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_read_crossbar_vdut",
        operation_form="AXI4 AR/R burst",
        protocol_scope=("AXI4 read-only profile",),
        port_shape="N ingress -> M egress",
        summary=(
            "Route accepted AR and restore R ownership with manager-local "
            "RID locks and subordinate-local raw-ID owner queues."
        ),
        required_inputs=(
            "AXI4 read-only InterfaceProtocol",
            "ingress and egress port names",
            "address routes",
        ),
        example="showcase/demos/system/axi4_read_2x4_crossbar",
    ),
    VirtualDutRecipe(
        id="amba.fabric.axi4-write-crossbar",
        title="AXI4 AW/W/B crossbar",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_axi4_write_crossbar_vdut",
        operation_form="AXI4 AW/W/B burst",
        protocol_scope=("AXI4 write-only profile",),
        port_shape="N ingress -> M egress",
        summary=(
            "FIFO-join AW/W bursts, route complete write batches, and restore "
            "B ownership with manager-local BID destination locks."
        ),
        required_inputs=(
            "AXI4 write-only InterfaceProtocol",
            "ingress and egress port names",
            "address routes",
        ),
    ),
    VirtualDutRecipe(
        id="amba.fabric.axi4-read-demux",
        title="AXI4 AR/R demultiplexer (1×M)",
        kind=Kind.FABRIC,
        layer=Layer.INTEGRATION,
        tier=Tier.CONVENIENCE,
        factory_path=f"{_AMBA}:build_axi4_read_demux_vdut",
        operation_form="AXI4 AR/R burst",
        protocol_scope=("AXI4 read-only profile",),
        port_shape="1 ingress -> N egress",
        summary=(
            "Specialize the generic AXI4 AR/R crossbar to one manager-facing ingress."
        ),
        required_inputs=(
            "AXI4 read-only InterfaceProtocol",
            "egress port names",
            "address routes",
        ),
        example=(
            "showcase/demos/system/axi4_single_manager_read_demux"
        ),
    ),

    # One generic bridge avoids an N-by-N family of pair-named implementations.
    VirtualDutRecipe(
        id="amba.bridge.serial",
        title="AMBA serial bridge",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_AMBA}:build_amba_serial_bridge_vdut",
        operation_form="selected from ingress interface shape",
        protocol_scope=("AXI4", "AXI4-Lite", "AHB-Lite/AHB5", "APB3/APB4/APB5"),
        port_shape="1 ingress -> 1 egress",
        summary="Select a supported access or burst translation from two AMBA interfaces.",
        required_inputs=("ingress InterfaceProtocol", "egress InterfaceProtocol"),
        example="showcase/demos/vdut/axi_ahb_apb_chain",
    ),
    VirtualDutRecipe(
        id="amba.bridge.serial-address",
        title="AMBA serial single-access bridge",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_amba_serial_address_bridge_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite", "AHB-Lite/AHB5", "APB3/APB4/APB5"),
        port_shape="1 ingress -> 1 egress",
        summary="Force the generic serial bridge through its single-access profile.",
        required_inputs=("ingress InterfaceProtocol", "egress InterfaceProtocol"),
    ),
    VirtualDutRecipe(
        id="amba.bridge.serial-burst",
        title="AMBA serial burst bridge",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.PROFILE,
        factory_path=f"{_AMBA}:build_amba_serial_burst_bridge_vdut",
        operation_form="address-burst",
        protocol_scope=("AXI4 ingress", "supported AMBA egress"),
        port_shape="1 ingress -> 1 egress",
        summary="Split one AXI4 burst into serialized child operations and fold completion.",
        required_inputs=("AXI4 ingress", "egress InterfaceProtocol"),
    ),
    VirtualDutRecipe(
        id="amba.bridge.axi4-to-ahb-lite",
        title="AXI4 to AHB-Lite bridge preset",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.CONVENIENCE,
        factory_path=f"{_AMBA}:build_axi4_to_ahb_lite_bridge_vdut",
        operation_form="address-burst",
        protocol_scope=("AXI4 ingress", "AHB-Lite egress"),
        port_shape="1 ingress -> 1 egress",
        summary="Apply the AXI4-to-AHB-Lite compatibility profile to the serial bridge.",
        required_inputs=("AXI4 InterfaceProtocol", "AHB-Lite InterfaceProtocol"),
    ),
    VirtualDutRecipe(
        id="amba.bridge.axi4-to-apb",
        title="AXI4 to APB bridge preset",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.CONVENIENCE,
        factory_path=f"{_AMBA}:build_axi4_to_apb_bridge_vdut",
        operation_form="address-burst",
        protocol_scope=("AXI4 ingress", "APB egress"),
        port_shape="1 ingress -> 1 egress",
        summary="Apply the AXI4-to-APB compatibility profile to the serial bridge.",
        required_inputs=("AXI4 InterfaceProtocol", "APB InterfaceProtocol"),
    ),
    VirtualDutRecipe(
        id="amba.bridge.axi4-lite-to-apb",
        title="AXI4-Lite to APB bridge preset",
        kind=Kind.BRIDGE,
        layer=Layer.INTEGRATION,
        tier=Tier.CONVENIENCE,
        factory_path=f"{_AMBA}:build_axi4_lite_to_apb_bridge_vdut",
        operation_form="address-access",
        protocol_scope=("AXI4-Lite ingress", "APB egress"),
        port_shape="1 ingress -> 1 egress",
        summary="Apply the AXI4-Lite-to-APB compatibility profile to the serial bridge.",
        required_inputs=("AXI4-Lite InterfaceProtocol", "APB InterfaceProtocol"),
    ),

    # Control-interface integration products.
    VirtualDutRecipe(
        id="control.interrupt.edge-controller",
        title="Edge interrupt controller",
        kind=Kind.CONTROL,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_CONTROL}:build_edge_interrupt_controller_vdut",
        operation_form="notification",
        protocol_scope=("interrupt notification interface",),
        port_shape="N ingress + 1 target",
        summary="Bind the priority/EOI controller to edge-notification ports.",
        required_inputs=("interrupt InterfaceProtocol", "source count"),
        example="showcase/demos/vdut/interrupt_control_plane",
    ),
    VirtualDutRecipe(
        id="control.interrupt.edge-target",
        title="Edge interrupt target",
        kind=Kind.CONTROL,
        layer=Layer.INTEGRATION,
        tier=Tier.PRIMARY,
        factory_path=f"{_CONTROL}:build_edge_interrupt_target_vdut",
        operation_form="notification",
        protocol_scope=("interrupt notification interface",),
        port_shape="1 target",
        summary="Bind an explicit-EOI notification target to the control interface.",
        required_inputs=("interrupt InterfaceProtocol",),
        example="showcase/demos/vdut/interrupt_control_plane",
    ),
)
