"""VirtualDut recipes whose exposed ports use AMBA interface families."""

from .chi import (
    ChiIssueHCacheVdutAssembly,
    attach_chi_issue_h_coherence,
    bind_chi_issue_h_cache_vdut,
    build_chi_issue_h_cache_vdut,
)
from .endpoints import (
    build_amba_queued_address_responder_vdut,
    build_amba_sensor_fifo_vdut,
    build_amba_serialized_memory_copy_vdut,
    build_ahb_address_space_vdut,
    build_ahb_blackhole_sink_vdut,
    build_ahb_idle_source_vdut,
    build_apb_address_space_vdut,
    build_apb_blackhole_sink_vdut,
    build_apb_idle_source_vdut,
    build_axi4_address_space_vdut,
    build_axi4_blackhole_sink_vdut,
    build_axi4_idle_source_vdut,
    build_axi4_lite_address_space_vdut,
    build_axi4_stream_capture_vdut,
)
from .fabrics import (
    Axi4BurstAssemblyProfile,
    Axi4ReadRouteTableProfile,
    Axi4WriteRouteTableProfile,
    build_ahb_address_fabric_vdut,
    build_apb_address_fabric_vdut,
    build_axi4_read_crossbar_vdut,
    build_axi4_read_demux_vdut,
    build_axi4_write_crossbar_vdut,
    build_axi4_lite_address_crossbar_vdut,
    build_axi4_lite_address_fabric_vdut,
)
from .bridges import (
    build_amba_serial_bridge_vdut,
    build_amba_serial_address_bridge_vdut,
    build_amba_serial_burst_bridge_vdut,
    build_axi4_lite_to_apb_bridge_vdut,
    build_axi4_to_ahb_lite_bridge_vdut,
    build_axi4_to_apb_bridge_vdut,
)

__all__ = [
    "Axi4BurstAssemblyProfile",
    "Axi4ReadRouteTableProfile",
    "Axi4WriteRouteTableProfile",
    "ChiIssueHCacheVdutAssembly",
    "attach_chi_issue_h_coherence",
    "bind_chi_issue_h_cache_vdut",
    "build_amba_queued_address_responder_vdut",
    "build_amba_sensor_fifo_vdut",
    "build_amba_serialized_memory_copy_vdut",
    "build_amba_serial_bridge_vdut",
    "build_amba_serial_address_bridge_vdut",
    "build_amba_serial_burst_bridge_vdut",
    "build_ahb_address_fabric_vdut",
    "build_ahb_address_space_vdut",
    "build_ahb_blackhole_sink_vdut",
    "build_ahb_idle_source_vdut",
    "build_apb_address_fabric_vdut",
    "build_apb_address_space_vdut",
    "build_apb_blackhole_sink_vdut",
    "build_apb_idle_source_vdut",
    "build_axi4_read_crossbar_vdut",
    "build_axi4_read_demux_vdut",
    "build_axi4_write_crossbar_vdut",
    "build_axi4_address_space_vdut",
    "build_axi4_blackhole_sink_vdut",
    "build_axi4_idle_source_vdut",
    "build_axi4_lite_address_crossbar_vdut",
    "build_axi4_lite_address_fabric_vdut",
    "build_axi4_lite_address_space_vdut",
    "build_axi4_lite_to_apb_bridge_vdut",
    "build_axi4_to_ahb_lite_bridge_vdut",
    "build_axi4_to_apb_bridge_vdut",
    "build_axi4_stream_capture_vdut",
    "build_chi_issue_h_cache_vdut",
]
